### ISSUE TITLE
crash when creating or joining singleplayer world

### ISSUE THREAD

**Issue by thimblebird** [AlmostReliable/ponderjs#10]
### Version

1.1.11-deobf

### Crash Report

https://pastebin.com/HyVZNiST

### Additional Context

Yes

### Modifications

https://www.curseforge.com/minecraft/modpacks/create-au-gratin

this still uses old ponderjs, then i updated ponderjs (why does the curseforge jar has `-deobf` in the name?) and i can't create or join a world anymore

i haven't uploaded ponderjs to the multiplayer server yet so can't confirm if this is a server thing

### Did the crash happen in singleplayer or on a server?

Singleplayer

**Comment by LLytho** [comment]
oooooops. Our CI might uploaded the wrong file 😅

**Comment by LLytho** [comment]
I manually added the right ponder file. You might need to redownload. Not sure if CF will understand this.

**Comment by thimblebird** [comment]
after installing the new version, it automatically installed `Create Fabric` in the curseforge launcher

//e: should've mentioned i'm on forge 🙈

**Comment by rlnt** [comment]
Fixed it. Thanks for the report. Lytho added the wrong dependency.
