### ISSUE TITLE
AE2 Controllers only render properly when one is already being rendered in the world

### ISSUE THREAD

**Issue by aaronhowser1** [AlmostReliable/ponderjs#11]
### Version

ponderjs-1.19.2-1.1.11

### Describe the bug!

https://user-images.githubusercontent.com/15698722/219934186-03799e8f-c807-4b1d-b451-2caeeb5ae6e5.mp4

When there's no functioning AE2 Controller being rendered in the world, Controllers in Ponders just get stuck in the first frame of their animation.

![javaw_2023-02-19_01-07-23](https://user-images.githubusercontent.com/15698722/219934217-25ce2d80-3161-41b6-bcc7-600b2d73a6ba.png)
With this, or when teleported somewhere without Controllers, the bug happens.

![javaw_2023-02-19_01-07-04](https://user-images.githubusercontent.com/15698722/219934225-1bf4ccc0-d0e8-40de-b6a7-f8ab15e0e39d.png)
With this, Controllers in Ponders animate correctly.

https://user-images.githubusercontent.com/15698722/219934234-d93c2ca1-2307-4153-8caf-112d2be9cb87.mp4

### Log

https://gist.github.com/518c26ac6933bfddb5c020ad384dc176

### Additional Context

Yes

### Modifications

Apotheosis-1.19.2-6.0.3.jar.disabled
jeed-1.19.2-1.18.jar.disabled
thermal_dynamics-1.19.2-10.2.1b.14.jar.disabled
thermal_foundation-1.19.2-10.2.0.47.jar.disabled
3dskinlayers-forge-1.5.2-mc1.19.1.jar
AI-Improvements-1.19.2-0.5.2.jar
alchemistry-1.19.2-2.2.3.jar
alchemylib-1.19.2-1.0.19.jar
alexsmobs-1.21.1.jar
almostunified-forge-1.19.2-0.3.5.jar
AmbientEnvironment-forge-1.19.2-8.0+3.jar
appleskin-forge-mc1.19-2.4.2.jar
Applied-Botanics-1.4.2.jar
appliedenergistics2-forge-12.9.2.jar
architectury-6.5.69-forge.jar
ars_nouveau-1.19.2-3.12.1.jar
AttributeFix-Forge-1.19.2-17.1.3.jar
AutoRegLib-1.8.2-55.jar
balm-4.5.3.jar
BetterAdvancements-1.19.2-0.3.0.148.jar
Bookshelf-Forge-1.19.2-16.2.16.jar
Botania-1.19.2-437-FORGE.jar
buildinggadgets-3.16.1-build.15+mc1.19.2.jar
catalogue-1.7.0-1.19.2.jar
chemlib-1.19.2-2.0.16.jar
chisels-and-bits-forge-1.3.126.jar
citadel-2.1.1-1.19.jar
ClickMachine-1.19.2-7.0.0.jar
clienttweaks-forge-1.19-8.1.0.jar
climbladdersfast-3.0.6-1.19-forge.jar
cloth-config-8.2.88-forge.jar
Clumps-forge-1.19.2-9.0.0+14.jar
CNB-1.19-1.5.1.jar
CodeChickenLib-1.19.2-4.3.1.481-universal.jar
cofh_core-1.19.2-10.2.1.40.jar
CommonCapabilities-1.19.2-2.9.0.jar
compactmachines-5.1.0.jar
Compressium-2.1.1-build.8+mc1.19.jar
configured-2.0.1-1.19.2.jar
Controlling-forge-1.19.2-10.0+7.jar
CosmeticArmorReworked-1.19.2-v1a.jar
create-1.19.2-0.5.0.i.jar
create-confectionery1.19.2_v1.0.8.jar
createoreexcavation-1.19-1.0.0.jar
creeperoverhaul-2.0.6-forge.jar
CTM-1.19.2-1.1.6+8.jar
curios-forge-1.19.2-5.1.2.2.jar
cursedearth-1.19.2-5.jar
CyclopsCore-1.19.2-1.17.5.jar
dankstorage-1.19.2-5.1.6.jar
DarkUtilities-Forge-1.19.2-13.1.7.jar
defaultoptions-forge-1.19-15.0.0.jar
dummmmmmy-1.19.2-1.7.0.jar
DungeonsArise-1.19.2-2.1.54-release.jar
eccentrictome-1.19.2-1.9.1.jar
effective_fg-1.3.4.jar
effortlessbuilding-1.19.2-3.0.jar
elevatorid-1.19.2-1.8.9.jar
Emojiful-Forge-1.19.2-4.0.4-all.jar
EnchantmentDescriptions-Forge-1.19.2-13.0.14.jar
EnderStorage-1.19.2-2.10.1.181-universal.jar
entangled-1.3.13-forge-mc1.19.jar
entangledfix-1.0.jar
EquipmentCompare-1.19.2-forge-1.3.2.jar
EvilCraft-1.19.2-1.2.15.jar
ExplorersCompass-1.19.2-1.3.0-forge.jar
FastFurnace-1.19.2-7.0.0.jar
FastLeafDecay-30.jar
FastSuite-1.19.2-4.0.0.jar
FastWorkbench-1.19.2-7.0.1.jar
ferritecore-5.0.3-forge.jar
findme-3.1.0-forge.jar
FramedBlocks-6.7.0.jar
ftb-chunks-forge-1902.3.15-build.233.jar
ftb-essentials-1902.1.10-build.47.jar
ftb-library-forge-1902.3.13-build.175.jar
ftb-quests-forge-1902.4.8-build.188.jar
ftb-quests-forge-1902.4.8-build.190.jar
ftb-ranks-forge-1902.1.14-build.70.jar
ftb-teams-forge-1902.2.12-build.95.jar
ftb-ultimine-forge-1902.3.5-build.65.jar
functionalstorage-1.19.2-1.1.3.jar
geckolib-forge-1.19-3.1.39.jar
glassential-forge-1.19-1.2.4.jar
grappling_hook_mod-1.19.2-1.19.2-v13.jar
HostileNeuralNetworks-1.19.2-4.0.2.jar
Iceberg-1.19.2-forge-1.1.4.jar
immersive_weathering-1.19.2-1.2.8-forge.jar
incontrol-1.19-7.1.3.jar
IntegratedCrafting-1.19.2-1.1.0.jar
IntegratedDynamics-1.19.2-1.15.1.jar
integratednbt-1.19.2-1.6.0.jar
IntegratedTerminals-1.19.2-1.4.4.jar
IntegratedTunnels-1.19.2-1.8.18.jar
inventoryessentials-forge-1.19-5.0.0.jar
inventorysorter-1.19.2-21.0.4.jar
ironchest-1.19.2-14.2.7.jar
item-filters-forge-1902.2.9-build.46.jar
jecalculation-forge-1.19.2-4.0.2.jar
kleeslabs-forge-1.19-12.1.0.jar
kotlinforforge-3.10.0-all.jar
kubejs-forge-1902.6.0-build.135.jar
laserio-1.5.2.jar
LegendaryTooltips-1.19.2-forge-1.4.0.jar
light-overlay-7.0.1-forge.jar
littlecontraptions-forge-1.19.2.0.jar
littlelogistics-mc1.19.2-v1.3.1.jar
lootr-1.19-0.3.22.59.jar
mahoutsukai-1.19.2-v1.34.39.jar
mcjtylib-1.19-7.1.5.jar
megacells-forge-0.0.0-1.19.2(1).jar
Mekanism-1.19.2-10.3.8.477.jar
MekanismAdditions-1.19.2-10.3.8.477.jar
MekanismGenerators-1.19.2-10.3.8.477.jar
MekanismTools-1.19.2-10.3.8.477.jar
merequester-1.19.2-1.0.3.jar
mob_grinding_utils-1.19.2-0.4.47.jar
modnametooltip-1.19-1.19.0.jar
modonomicon-1.19.2-1.25.0.jar
modular-routers-1.19.2-10.2.0-3.jar
moonlight-1.19.2-2.2.7-forge.jar
moredragoneggs-3.2.jar
MouseTweaks-forge-mc1.19-2.23.jar
mutil-1.19.2-5.1.0.jar
NaturesAura-37.7.jar
NaturesCompass-1.19.2-1.10.0-forge.jar
occultism-1.19.2-1.70.0.jar
overloadedarmorbar-1.19.2-7.jar
Patchouli-1.19.2-77.jar
PigPen-Forge-1.19.2-11.1.2.jar
Placebo-1.19.2-7.1.2.jar
pneumaticcraft-repressurized-1.19.2-4.3.1-20.jar
polylib-forge-1900.0.2-build.42.jar
ponderjs-1.19.2-1.1.11.jar
prefab-1.9.2.5.jar
PrettyPipes-1.13.6.jar
Prism-1.19.1-1.0.2.jar
probejs-4.3.0-forge.jar
Quark-3.4-389.jar
QuarkOddities-1.18.jar
questsadditions-1.19.2-1.4.1.jar
REIPluginCompatibilities-forge-9.0.44.jar
repurposed_structures_forge-6.3.11+1.19.2.jar
rer-2.6.1.jar
rftoolsbase-1.19.1-4.1.4.jar
rftoolsbuilder-1.19.1-5.2.3.jar
rftoolscontrol-1.19-6.1.2.jar
rftoolspower-1.19-5.1.1.jar
rftoolsstorage-1.19-4.1.0.jar
rftoolsutility-1.19-5.1.4.jar
rhino-forge-1902.2.2-build.264.jar
RoughlyEnoughItems-9.1.591.jar
RoughlyEnoughProfessions-forge-1.19.2-1.1.3.jar
RoughlyEnoughTrades-1.19-1.0.jar
rubidium_extras-1.19.2_v1.3.2.jar
rubidium-0.6.2.jar
Runelic-Forge-1.19.2-14.1.3.jar
serverconfigupdater-3.1.jar
SimpleDiscordRichPresence-forge-3.0.4-build.27+mc1.19.2.jar
simplylight-1.19.2-1.4.5-build.42.jar
SmartBrainLib-forge-1.19.2-1.8.jar
smoothchunk-1.19.1-2.0.jar
soulshards-1.19-1.3.4.jar
spark-1.10.29-forge.jar
squatgrow-3.0.0-build.33+mc1.19.2.jar
starlight-1.1.1+forge.cf5b10b.jar
Steam_Rails-1.19.2-1.1.1.jar
SuperFactoryManager-1.19.2-4.4.4.jar
supermartijn642configlib-1.1.6b-forge-mc1.19.jar
supermartijn642corelib-1.1.2-forge-mc1.19.jar
supplementaries-1.19.2-2.2.50.jar
theoneprobe-1.19-6.2.2.jar
tinygates-1.19.2-3.1.2.jar
tinypipes-3.1.3.jar
tinyredstone-1.19.2-4.1.3.jar
Tips-Forge-1.19.2-8.0.27.jar
TipTheScales-forge-1.19.2-6.0.10.jar
titanium-1.19.2-3.7.2-26.jar
trashcans-1.0.17-forge-mc1.19.jar
xnet-1.19-5.1.2.jar
yeetusexperimentus-1.0.1-build.2+mc1.19.1.jar
YungsApi-1.19.2-Forge-3.8.6.jar
YungsBetterDesertTemples-1.19.2-Forge-2.2.1.jar
YungsBetterDungeons-1.19.2-Forge-3.2.2.jar
YungsBetterMineshafts-1.19.2-Forge-3.2.0.jar
YungsBetterStrongholds-1.19.2-Forge-3.2.0.jar
YungsBridges-1.19.2-Forge-3.1.0.jar
megacells-forge-2.0.0-beta.7-1.19.2.jard
tetra-1.19.2-5.0.1.jard

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
Confirmed to be an issue of Rubidium by an AE2 dev. Sorry for the inconvenience but this is not something we can fix on our end.

**Comment by shartte** [comment]
This is rubidium related.

**Comment by shartte** [comment]
Oh, commented at exactly the same time :-D
