### ISSUE TITLE
[1.19.2 - Modrinth] latest Forge version is not game-ready build

### ISSUE THREAD

**Issue by ColonelGerdauf** [AlmostReliable/ponderjs#13]
### Version

1.1.12 - Forge

### Describe the bug!

The version for 1.19.2 on Forge is a `deobf` version, a deobfuscated build, which is not intended for general use and gameplay.

I had installed this from Modrinth, and it was causing startup crashing, which took a while to troubleshoot, but it was pinned down to this mod being of the wrong type.

### Additional Context

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by LLytho** [comment]
Hey,

I fixed it on CF but forgot about MR. I manually uploaded the correct file now.
