### ISSUE TITLE
1.20.1 Version Compatibility Request

### ISSUE THREAD

**Issue by M0nkeyPr0grammer** [AlmostReliable/ponderjs#17]
### Describe the feature/addition!

I observed that KubeJS has recently been updated. In light of this, I would like to formally request an update for PonderJS as well.

### Why would like to see this feature/addition?

Allows me to use it in my future modpack version release for 1.20.1

**Comment by rlnt** [comment]
Implemented in https://github.com/AlmostReliable/ponderjs/commit/3c77ae4fe8ee96d4f88b77d1cd3fd1ecf20b64de
Should be available shortly.

**Comment by adaliszk** [comment]
Is there a Fabric build somewhere, or does that need more work?

**Comment by LLytho** [comment]
> Is there a Fabric build somewhere, or does that need more work?

Fabric Release action runs. Will be up shortly.
