### ISSUE TITLE
I Crash when I hit F3+T In Fabric 1.20.1

### ISSUE THREAD

**Issue by FireNneon** [AlmostReliable/ponderjs#18]
### Minecraft Version

1.20.1

### Mod Version

Ponder for Kubejs 1.20.1-1.3.0+fabric

### Crash Report

https://gist.github.com/FireNneon/70de0038f1963aab63915c32f76eaed1

### Log

https://gist.github.com/FireNneon/7b819a5850bde60d1aa900e170f3264b

### Additions and Modifications

No

### Additions and Modifications Description

Fabric Version:   Fabric Loader 0.15.10
Architectury API:   9.2.14+fabric
Kubejs:   2001.6.5-build.7+fabric
Create Fabric:   0.5.1-f-build.1417+mc1.20.1
Rhino:   2001.2.2-build.18+fabric
Fabric API:   0.92.1+1.20.1

Launcher: Modrinth

### Did the crash happen in singleplayer or on a server?

Singleplayer

**Comment by LLytho** [comment]
Updated and pushed. Should be available soon on Curseforge.

**Comment by FireNneon** [comment]
Oh, awesome.
