### ISSUE TITLE
Add Config

### ISSUE THREAD

**Issue by Qi-Month** [AlmostReliable/ponderjs#19]
### Describe the feature/addition!

Add Config
Can select the path to the language file and the default language

### Why would like to see this feature/addition?

For people with other languages, the default English will be very bad.

**Comment by rlnt** [comment]
English is the default localization language of Minecraft. If translations are missing, it will always fall back to English. You can provide translations for other languages via datapacks which is really easy with KubeJS. Just use the localization keys from `kubejs/assets/ponderjs_generated/lang/en_us.json`.
