### ISSUE TITLE
Be able to ponder items with an NBT

### ISSUE THREAD

**Issue by Gurkysword12** [AlmostReliable/ponderjs#8]
### Describe the feature/addition!

Would love to be able to ponder items/blocks that have an nbt value. Like press w on an item with nbt

### Why would like to see this feature/addition?

It would be really helpful.

**Comment by LLytho** [comment]
Will be added in the future. But rn I don't know when exactly.

**Comment by TheRealMrSnowman** [comment]
has this been implemented yet?

**Comment by LLytho** [comment]
No and currently unsure if it will be added to PonderJS. I think it's a feature that should be part of Ponder itself.

**Comment by TheRealMrSnowman** [comment]
Looking at the functions provided by ponder it seems there is a createItemEntity function however it seems to not work properly when done with PonderJS and the item just falls through the floor of the ponder and disappears. I'll mess around a bit and see if theres some way to edit the entity with the modifyEntity function to remove its gravity.
