### ISSUE TITLE
Crash on start (1.19.2)

### ISSUE THREAD

**Issue by Diversion98** [AlmostReliable/ponderjs#9]
### Version

1.19.2

### Describe the bug!

When Ponder for KubeJS is installed, Minecraft crashes on start with the following crash report +log

### Crash Report

https://pastebin.com/j5Wn8gZP

### Log

https://gist.github.com/Diversion98/6a0bc9cbf60e69daebbc93010eee03e6

### Additional Context

Yes

### Modifications

See crash report for added mods to the modpack.
123 mods are installed

### Did the issue happen in singleplayer or on a server?

Both

**Comment by LLytho** [comment]
Rhino made some breaking changes again. Will fix it today

**Comment by LLytho** [comment]
Uploaded to CF. Should be available soon. Thanks for the report.
